import { Article } from "../../types/IArticleList";

export const mockArticles: Article[] = [
    {
        id: 1,
        title: "Getting Started with React - A Comprehensive Guide for Beginners",
        category: "Frontend",
        status: "published",
        author: "John Doe",
        publishDate: "2024-03-15",
        lastModified: "2024-03-16",
        views: 1234,
        description:
            "Learn the basics of React and start building your first application with this comprehensive guide.",
        tags: ["React", "JavaScript", "Web Development"],
        priority: 9,
        wordCount: 2500,
        readTime: 12,
        likes: 45,
        comments: 12,
        children: [
            {
                id: 101,
                title: "React useState Deep Dive",
                category: "Frontend",
                status: "published",
                author: "John Doe",
                publishDate: "2024-03-15",
                lastModified: "2024-03-16",
                views: 234,
                description: "A deep dive into useState hook.",
                tags: ["React", "Hooks"],
                priority: 7,
                wordCount: 1200,
                readTime: 6,
                likes: 12,
                comments: 3,
                children: [
                    {
                        id: 201,
                        title: "React useState Advanced Patterns",
                        category: "Frontend",
                        status: "draft",
                        author: "John Doe",
                        publishDate: "2024-03-15",
                        lastModified: "2024-03-16",
                        views: 54,
                        description: "Advanced patterns for useState.",
                        tags: ["React", "Hooks"],
                        priority: 5,
                        wordCount: 800,
                        readTime: 4,
                        likes: 2,
                        comments: 0,
                    },
                ],
            },
        ],
    },
    {
        id: 2,
        title: "Advanced TypeScript Tips and Best Practices for Large Scale Applications",
        category: "Programming",
        status: "draft",
        author: "Jane Smith",
        publishDate: "2024-03-14",
        lastModified: "2024-03-15",
        views: 856,
        description: "Deep dive into TypeScript features and patterns that will help you build better applications.",
        tags: ["TypeScript", "Programming", "Best Practices"],
        priority: 7,
        wordCount: 3200,
        readTime: 16,
        likes: 32,
        comments: 8,
    },
    {
        id: 3,
        title: "Node.js Best Practices - Performance Optimization Guide",
        category: "Backend",
        status: "published",
        author: "Mike Johnson",
        publishDate: "2024-03-13",
        lastModified: "2024-03-14",
        views: 2341,
        description: "Learn how to optimize your Node.js applications for better performance.",
        tags: ["Node.js", "Performance", "Backend"],
        priority: 8,
        wordCount: 4100,
        readTime: 20,
        likes: 67,
        comments: 15,
    },
    // Add more mock data to demonstrate scrolling
    ...Array.from({ length: 50 }, (_, i) => ({
        id: i + 4,
        title: `Sample Article ${i + 4}`,
        category: ["Frontend", "Backend", "Programming"][i % 3],
        status: ["published", "draft", "archived"][i % 3] as Article["status"],
        author: ["John Doe", "Jane Smith", "Mike Johnson"][i % 3],
        publishDate: "2024-03-" + String(12 - (i % 12)).padStart(2, "0"),
        lastModified: "2024-03-" + String(13 - (i % 12)).padStart(2, "0"),
        views: Math.floor(Math.random() * 5000),
        description: `This is a sample article ${i + 4} description.`,
        tags: ["Sample", `Tag${i + 1}`],
        priority: Math.floor(Math.random() * 10) + 1,
        wordCount: Math.floor(Math.random() * 5000) + 1000,
        readTime: Math.floor(Math.random() * 25) + 5,
        likes: Math.floor(Math.random() * 100),
        comments: Math.floor(Math.random() * 30),
    })),
];
