import { IRoutePage } from "./IRoute";
import {
    RiDashboardLine,
    RiArticleLine,
    RiUserLine,
    RiSettingsLine,
    RiFileListLine,
    RiFileTextLine,
    RiTodoLine,
    RiCalendarLine,
    RiNotificationLine,
    RiMessageLine,
    RiMailLine,
    RiShieldLine,
    RiLoginBoxLine,
    RiUserAddLine,
    RiUserSearchLine,
    RiUserSettingsLine,
    RiErrorWarningLine,
    RiAppsLine,
    RiLayoutLine,
    RiAlertLine,
    RiLockPasswordLine,
} from "react-icons/ri";
import { Pages } from "./pageLazyLoad";
/**
 * @description 路由-菜单的配置列表
 * @description {key, icon, label} 菜单栏
 * @description {component, path, index, caseSensitive, children} 路由菜单
 * @description {index, path} - index为false时,path生效 - TODO:增加排序
 * @description {outlet, component} - outlet 为true时, component不生效
 * @description {menuShow} - 主体背景设置。设置为false时,菜单展示中不显示
 */
export const routes: IRoutePage[] = [
    {
        key: "dashboard",
        label: "仪表盘",
        icon: RiDashboardLine,
        path: "/",
        component: Pages.DashboardLayout,
        menuShow: true,
        auth: true,
        badge: { type: "success", dot: true },
        children: [
            {
                key: "dashboard-content",
                label: "仪表盘",
                path: "/dashboard",
                component: Pages.Dashboard,
                menuShow: true,
                auth: true,
            },
        ],
    },
    {
        key: "content",
        label: "内容管理",
        icon: RiAppsLine,
        path: "/content",
        component: Pages.DashboardLayout,
        menuShow: true,
        auth: true,
        tag: { type: "info", text: "推荐" },
        children: [
            {
                key: "article",
                label: "文章管理",
                icon: RiArticleLine,
                path: "article",
                component: Pages.ArticleLayout,
                menuShow: true,
                auth: true,
                badge: { type: "primary", count: 5 },
                children: [
                    {
                        key: "article-list",
                        label: "文章列表",
                        icon: RiFileListLine,
                        path: "list",
                        component: Pages.ArticleList,
                        menuShow: true,
                        auth: true,
                        badge: { type: "error", count: 3 },
                    },
                    {
                        key: "article-edit",
                        label: "文章编辑",
                        icon: RiFileTextLine,
                        path: "edit/:id",
                        component: Pages.ArticleEdit,
                        menuShow: false,
                        auth: true,
                    },
                    {
                        key: "article-create",
                        label: "创建文章",
                        icon: RiFileTextLine,
                        path: "edit",
                        component: Pages.ArticleEdit,
                        menuShow: true,
                        auth: true,
                        tag: { type: "warning", text: "新功能" },
                    },
                ],
            },
            {
                key: "todo",
                label: "待办事项",
                icon: RiTodoLine,
                path: "todo",
                component: Pages.Todo,
                menuShow: true,
                auth: true,
                badge: { type: "warning", count: 10 },
            },
            {
                key: "calendar",
                label: "日历",
                icon: RiCalendarLine,
                path: "calendar",
                component: Pages.Calendar,
                menuShow: true,
                auth: true,
            },
        ],
    },
    {
        key: "system",
        label: "系统管理",
        icon: RiLayoutLine,
        path: "/system",
        component: Pages.DashboardLayout,
        menuShow: true,
        auth: true,
        children: [
            {
                key: "user",
                label: "用户管理",
                icon: RiUserLine,
                path: "user",
                component: Pages.UserLayout,
                menuShow: true,
                auth: true,
                children: [
                    {
                        key: "user-list",
                        label: "用户列表",
                        icon: RiUserSearchLine,
                        path: "list",
                        component: Pages.UserList,
                        menuShow: true,
                        auth: true,
                    },
                    {
                        key: "user-profile",
                        label: "用户资料",
                        icon: RiUserSettingsLine,
                        path: "profile",
                        component: Pages.UserProfile,
                        menuShow: true,
                        auth: true,
                    },
                ],
            },
            {
                key: "notification",
                label: "通知",
                icon: RiNotificationLine,
                path: "notification",
                component: Pages.Notification,
                menuShow: true,
                auth: true,
                badge: { type: "error", count: 99 },
            },
            {
                key: "message",
                label: "消息",
                icon: RiMessageLine,
                path: "message",
                component: Pages.Message,
                menuShow: true,
                auth: true,
                badge: { type: "primary", count: 7 },
            },
            {
                key: "mail",
                label: "邮件",
                icon: RiMailLine,
                path: "mail",
                component: Pages.Mail,
                menuShow: true,
                auth: true,
                tag: { type: "success", text: "已同步" },
            },
            {
                key: "mail-template-edit",
                label: "邮件模板编辑",
                icon: RiMailLine,
                path: "mail-template-edit",
                component: Pages.MailTemplateEdit,
                menuShow: true,
                auth: true,
            },
            {
                key: "settings",
                label: "设置",
                icon: RiSettingsLine,
                path: "settings",
                component: Pages.Settings,
                menuShow: true,
                auth: true,
            },
            {
                key: "security",
                label: "安全",
                icon: RiShieldLine,
                path: "security",
                component: Pages.Security,
                menuShow: true,
                auth: true,
            },
        ],
    },
    // 错误页面路由组
    {
        key: "error",
        label: "错误页面",
        icon: RiAlertLine,
        path: "/error",
        component: Pages.DashboardLayout,
        menuShow: true,
        auth: false,
        children: [
            {
                key: "301",
                label: "301",
                icon: RiErrorWarningLine,
                path: "301",
                component: Pages.MovedPermanently,
                menuShow: true,
                auth: false,
            },
            {
                key: "404",
                label: "404",
                icon: RiErrorWarningLine,
                path: "404",
                component: Pages.NotFound,
                menuShow: true,
                auth: false,
            },
            {
                key: "500",
                label: "500",
                icon: RiErrorWarningLine,
                path: "500",
                component: Pages.ServerError,
                menuShow: true,
                auth: false,
            },
            {
                key: "503",
                label: "503",
                icon: RiErrorWarningLine,
                path: "503",
                component: Pages.ServiceUnavailable,
                menuShow: true,
                auth: false,
            },
        ],
    },
    {
        key: "components",
        label: "组件",
        icon: RiAppsLine,
        path: "/components",
        component: Pages.DashboardLayout,
        menuShow: true,
        auth: false,
        children: [
            {
                key: "dropdown-demo",
                label: "Dropdown",
                icon: RiAppsLine,
                path: "dropdown",
                component: Pages.DropdownDemo,
                menuShow: true,
                auth: false,
            },
        ],
    },

    {
        key: "login",
        label: "登录",
        icon: RiLoginBoxLine,
        path: "/login",
        component: Pages.Login,
        menuShow: false,
        auth: false,
    },
    {
        key: "register",
        label: "注册",
        icon: RiUserAddLine,
        path: "/register",
        component: Pages.Register,
        menuShow: false,
        auth: false,
    },
    {
        key: "forgot-password",
        label: "忘记密码",
        icon: RiLockPasswordLine,
        path: "/forgot-password",
        component: Pages.ForgotPassword,
        menuShow: false,
        auth: false,
    },
    // 通配符路由放在最后
    {
        key: "not-found",
        label: "404",
        path: "*",
        component: Pages.NotFound,
        menuShow: false,
        auth: false,
    },
];
