import { IRoutePage } from "./IRoute";
import {
    RiDashboardLine,
    RiArticleLine,
    RiUserLine,
    RiSettingsLine,
    RiFileListLine,
    RiFileTextLine,
    RiTodoLine,
    RiCalendarLine,
    RiNotificationLine,
    RiMessageLine,
    RiMailLine,
    RiShieldLine,
    RiLoginBoxLine,
    RiUserAddLine,
    RiUserSearchLine,
    RiUserSettingsLine,
    RiErrorWarningLine,
    RiAppsLine,
    RiLayoutLine,
} from "react-icons/ri";
import pageLazyLoad from "./pageLazyLoad";
import DashboardLayout from "@layout/DashboardLayout";

/**
 * @description 路由-菜单的配置列表
 * @description {key, icon, label} 菜单栏
 * @description {component, path, index, caseSensitive, children} 路由菜单
 * @description {index, path} - index为false时,path生效 - TODO:增加排序
 * @description {outlet, component} - outlet 为true时, component不生效
 * @description {menuShow} - 主体背景设置。设置为false时,菜单展示中不显示
 */
export const routes: IRoutePage[] = [
    {
        key: "dashboard",
        label: "仪表盘",
        icon: RiDashboardLine,
        path: "/",
        component: DashboardLayout,
        menuShow: true,
        auth: true,
        children: [
            {
                key: "dashboard-content",
                label: "仪表盘",
                path: "dashboard",
                component: pageLazyLoad.Dashboard,
                menuShow: true,
                auth: true,
            },
        ],
    },
    {
        key: "content",
        label: "内容管理",
        icon: RiAppsLine,
        path: "/content",
        component: DashboardLayout,
        menuShow: true,
        auth: true,
        children: [
            {
                key: "article",
                label: "文章管理",
                icon: RiArticleLine,
                path: "article",
                component: pageLazyLoad.Article,
                menuShow: true,
                auth: true,
                children: [
                    {
                        key: "article-list",
                        label: "文章列表",
                        icon: RiFileListLine,
                        path: "list",
                        component: pageLazyLoad.ArticleList,
                        menuShow: true,
                        auth: true,
                    },
                    {
                        key: "article-edit",
                        label: "文章编辑",
                        icon: RiFileTextLine,
                        path: "edit",
                        component: pageLazyLoad.ArticleEdit,
                        menuShow: true,
                        auth: true,
                    },
                ],
            },
            {
                key: "todo",
                label: "待办事项",
                icon: RiTodoLine,
                path: "todo",
                component: pageLazyLoad.Todo,
                menuShow: true,
                auth: true,
            },
            {
                key: "calendar",
                label: "日历",
                icon: RiCalendarLine,
                path: "calendar",
                component: pageLazyLoad.Calendar,
                menuShow: true,
                auth: true,
            },
        ],
    },
    {
        key: "system",
        label: "系统管理",
        icon: RiLayoutLine,
        path: "/system",
        component: DashboardLayout,
        menuShow: true,
        auth: true,
        children: [
            {
                key: "user",
                label: "用户管理",
                icon: RiUserLine,
                path: "user",
                component: pageLazyLoad.User,
                menuShow: true,
                auth: true,
                children: [
                    {
                        key: "user-list",
                        label: "用户列表",
                        icon: RiUserSearchLine,
                        path: "list",
                        component: pageLazyLoad.UserList,
                        menuShow: true,
                        auth: true,
                    },
                    {
                        key: "user-profile",
                        label: "用户资料",
                        icon: RiUserSettingsLine,
                        path: "profile",
                        component: pageLazyLoad.UserProfile,
                        menuShow: true,
                        auth: true,
                    },
                ],
            },
            {
                key: "notification",
                label: "通知",
                icon: RiNotificationLine,
                path: "notification",
                component: pageLazyLoad.Notification,
                menuShow: true,
                auth: true,
            },
            {
                key: "message",
                label: "消息",
                icon: RiMessageLine,
                path: "message",
                component: pageLazyLoad.Message,
                menuShow: true,
                auth: true,
            },
            {
                key: "mail",
                label: "邮件",
                icon: RiMailLine,
                path: "mail",
                component: pageLazyLoad.Mail,
                menuShow: true,
                auth: true,
            },
            {
                key: "settings",
                label: "设置",
                icon: RiSettingsLine,
                path: "settings",
                component: pageLazyLoad.Settings,
                menuShow: true,
                auth: true,
            },
            {
                key: "security",
                label: "安全",
                icon: RiShieldLine,
                path: "security",
                component: pageLazyLoad.Security,
                menuShow: true,
                auth: true,
            },
        ],
    },
    {
        key: "login",
        label: "登录",
        icon: RiLoginBoxLine,
        path: "/login",
        component: pageLazyLoad.Login,
        menuShow: false,
        auth: false,
    },
    {
        key: "register",
        label: "注册",
        icon: RiUserAddLine,
        path: "/register",
        component: pageLazyLoad.Register,
        menuShow: false,
        auth: false,
    },
    // 错误页面路由
    {
        key: "404",
        label: "404",
        icon: RiErrorWarningLine,
        path: "/404",
        component: pageLazyLoad.NotFound,
        menuShow: false,
        auth: false,
    },
    {
        key: "500",
        label: "500",
        icon: RiErrorWarningLine,
        path: "/500",
        component: pageLazyLoad.ServerError,
        menuShow: false,
        auth: false,
    },
    {
        key: "503",
        label: "503",
        icon: RiErrorWarningLine,
        path: "/503",
        component: pageLazyLoad.ServiceUnavailable,
        menuShow: false,
        auth: false,
    },
    {
        key: "301",
        label: "301",
        icon: RiErrorWarningLine,
        path: "/301",
        component: pageLazyLoad.MovedPermanently,
        menuShow: false,
        auth: false,
    },
    {
        key: "error",
        label: "错误",
        icon: RiErrorWarningLine,
        path: "/error",
        component: pageLazyLoad.Error,
        menuShow: false,
        auth: false,
    },
    {
        key: "error-boundary",
        label: "组件错误",
        icon: RiErrorWarningLine,
        path: "/error-boundary",
        component: pageLazyLoad.ErrorBoundary,
        menuShow: false,
        auth: false,
    },
    // 通配符路由放在最后
    {
        key: "not-found",
        label: "404",
        path: "*",
        component: pageLazyLoad.NotFound,
        menuShow: false,
        auth: false,
    },
];
